---

- name: create web directory
  file:
    path: ~/backend_app
    state: directory

- name: "wait 600 seconds for target connection to become reachable/usable."
  ansible.builtin.wait_for_connection:
  timeout: 900
- name: Copy backend compressed file 
  #become: true
  copy:
    src: /home/circleci/project/artifact.tar.gz
    dest: ~/backend_app
- name: Extract backend files
  # become: true
  shell: |
    cd ~/backend_app
    tar -vxf artifact.tar.gz
    #rm artifact.tar.gz
    ls
  register: output


- debug:
    var: output

- name : Compile and start app 
  # become : true 
  shell : | 
    cd ~/backend_app
    sudo apt install npm -y
    npm install
    
    pm2 stop default
    pm2 start npm -- start