---
- name: "Update/upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "Create directory"
  become: true
  file:
    path: /home/ubuntu/backend/
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755


- name: Copy files
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend/
    owner: ubuntu
    group: ubuntu
    mode: 0755

# - name: Unarchive a file that is already on the remote machine
#   ansible.builtin.unarchive:
#     src: ~/backend/artifact.tar.gz
#     dest: ~/backend
#     remote_src: yes
- name: unarchive backend files
  become: yes
  shell: |
    cd /home/ubuntu/backend/
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: "Install nodejs and npm."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2."
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Build package"
  become: true
  command: npm run build
  args:
    chdir: /home/ubuntu/backend
    
- name: "Start server"
  become: true
  shell: |
    pwd
    ls
    cd dist
    pm2 start npm --name 'udapeople' -- start
  args:
    chdir: /home/ubuntu/backend/